/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/favusersproducts": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favusersproducts.id"];
          userid?: parameters["rowFilter.favusersproducts.userid"];
          productid?: parameters["rowFilter.favusersproducts.productid"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["favusersproducts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** favusersproducts */
          favusersproducts?: definitions["favusersproducts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favusersproducts.id"];
          userid?: parameters["rowFilter.favusersproducts.userid"];
          productid?: parameters["rowFilter.favusersproducts.productid"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favusersproducts.id"];
          userid?: parameters["rowFilter.favusersproducts.userid"];
          productid?: parameters["rowFilter.favusersproducts.productid"];
        };
        body: {
          /** favusersproducts */
          favusersproducts?: definitions["favusersproducts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/favusersrecipes": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favusersrecipes.id"];
          userid?: parameters["rowFilter.favusersrecipes.userid"];
          recipeid?: parameters["rowFilter.favusersrecipes.recipeid"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["favusersrecipes"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** favusersrecipes */
          favusersrecipes?: definitions["favusersrecipes"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favusersrecipes.id"];
          userid?: parameters["rowFilter.favusersrecipes.userid"];
          recipeid?: parameters["rowFilter.favusersrecipes.recipeid"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favusersrecipes.id"];
          userid?: parameters["rowFilter.favusersrecipes.userid"];
          recipeid?: parameters["rowFilter.favusersrecipes.recipeid"];
        };
        body: {
          /** favusersrecipes */
          favusersrecipes?: definitions["favusersrecipes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/ingredients": {
    get: {
      parameters: {
        query: {
          ingredientid?: parameters["rowFilter.ingredients.ingredientid"];
          productid?: parameters["rowFilter.ingredients.productid"];
          recipeid?: parameters["rowFilter.ingredients.recipeid"];
          productcount?: parameters["rowFilter.ingredients.productcount"];
          measure?: parameters["rowFilter.ingredients.measure"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ingredients"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** ingredients */
          ingredients?: definitions["ingredients"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          ingredientid?: parameters["rowFilter.ingredients.ingredientid"];
          productid?: parameters["rowFilter.ingredients.productid"];
          recipeid?: parameters["rowFilter.ingredients.recipeid"];
          productcount?: parameters["rowFilter.ingredients.productcount"];
          measure?: parameters["rowFilter.ingredients.measure"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          ingredientid?: parameters["rowFilter.ingredients.ingredientid"];
          productid?: parameters["rowFilter.ingredients.productid"];
          recipeid?: parameters["rowFilter.ingredients.recipeid"];
          productcount?: parameters["rowFilter.ingredients.productcount"];
          measure?: parameters["rowFilter.ingredients.measure"];
        };
        body: {
          /** ingredients */
          ingredients?: definitions["ingredients"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/productinmeal": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.productinmeal.id"];
          mealid?: parameters["rowFilter.productinmeal.mealid"];
          productid?: parameters["rowFilter.productinmeal.productid"];
          isEaten?: parameters["rowFilter.productinmeal.isEaten"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["productinmeal"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** productinmeal */
          productinmeal?: definitions["productinmeal"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.productinmeal.id"];
          mealid?: parameters["rowFilter.productinmeal.mealid"];
          productid?: parameters["rowFilter.productinmeal.productid"];
          isEaten?: parameters["rowFilter.productinmeal.isEaten"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.productinmeal.id"];
          mealid?: parameters["rowFilter.productinmeal.mealid"];
          productid?: parameters["rowFilter.productinmeal.productid"];
          isEaten?: parameters["rowFilter.productinmeal.isEaten"];
        };
        body: {
          /** productinmeal */
          productinmeal?: definitions["productinmeal"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          productid?: parameters["rowFilter.products.productid"];
          gtincode?: parameters["rowFilter.products.gtincode"];
          name?: parameters["rowFilter.products.name"];
          photolink?: parameters["rowFilter.products.photolink"];
          category?: parameters["rowFilter.products.category"];
          verified?: parameters["rowFilter.products.verified"];
          proposaluserid?: parameters["rowFilter.products.proposaluserid"];
          imgCode?: parameters["rowFilter.products.imgCode"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** products */
          products?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          productid?: parameters["rowFilter.products.productid"];
          gtincode?: parameters["rowFilter.products.gtincode"];
          name?: parameters["rowFilter.products.name"];
          photolink?: parameters["rowFilter.products.photolink"];
          category?: parameters["rowFilter.products.category"];
          verified?: parameters["rowFilter.products.verified"];
          proposaluserid?: parameters["rowFilter.products.proposaluserid"];
          imgCode?: parameters["rowFilter.products.imgCode"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          productid?: parameters["rowFilter.products.productid"];
          gtincode?: parameters["rowFilter.products.gtincode"];
          name?: parameters["rowFilter.products.name"];
          photolink?: parameters["rowFilter.products.photolink"];
          category?: parameters["rowFilter.products.category"];
          verified?: parameters["rowFilter.products.verified"];
          proposaluserid?: parameters["rowFilter.products.proposaluserid"];
          imgCode?: parameters["rowFilter.products.imgCode"];
        };
        body: {
          /** products */
          products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/recipeinmeal": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.recipeinmeal.id"];
          mealid?: parameters["rowFilter.recipeinmeal.mealid"];
          recipeid?: parameters["rowFilter.recipeinmeal.recipeid"];
          isEaten?: parameters["rowFilter.recipeinmeal.isEaten"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["recipeinmeal"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** recipeinmeal */
          recipeinmeal?: definitions["recipeinmeal"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.recipeinmeal.id"];
          mealid?: parameters["rowFilter.recipeinmeal.mealid"];
          recipeid?: parameters["rowFilter.recipeinmeal.recipeid"];
          isEaten?: parameters["rowFilter.recipeinmeal.isEaten"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.recipeinmeal.id"];
          mealid?: parameters["rowFilter.recipeinmeal.mealid"];
          recipeid?: parameters["rowFilter.recipeinmeal.recipeid"];
          isEaten?: parameters["rowFilter.recipeinmeal.isEaten"];
        };
        body: {
          /** recipeinmeal */
          recipeinmeal?: definitions["recipeinmeal"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/recipes": {
    get: {
      parameters: {
        query: {
          recipeid?: parameters["rowFilter.recipes.recipeid"];
          photolink?: parameters["rowFilter.recipes.photolink"];
          title?: parameters["rowFilter.recipes.title"];
          description?: parameters["rowFilter.recipes.description"];
          recipetype?: parameters["rowFilter.recipes.recipetype"];
          mealportions?: parameters["rowFilter.recipes.mealportions"];
          kcalperportion?: parameters["rowFilter.recipes.kcalperportion"];
          verified?: parameters["rowFilter.recipes.verified"];
          proposaluserid?: parameters["rowFilter.recipes.proposaluserid"];
          isvegan?: parameters["rowFilter.recipes.isvegan"];
          isvegetarian?: parameters["rowFilter.recipes.isvegetarian"];
          imgCode?: parameters["rowFilter.recipes.imgCode"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["recipes"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** recipes */
          recipes?: definitions["recipes"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          recipeid?: parameters["rowFilter.recipes.recipeid"];
          photolink?: parameters["rowFilter.recipes.photolink"];
          title?: parameters["rowFilter.recipes.title"];
          description?: parameters["rowFilter.recipes.description"];
          recipetype?: parameters["rowFilter.recipes.recipetype"];
          mealportions?: parameters["rowFilter.recipes.mealportions"];
          kcalperportion?: parameters["rowFilter.recipes.kcalperportion"];
          verified?: parameters["rowFilter.recipes.verified"];
          proposaluserid?: parameters["rowFilter.recipes.proposaluserid"];
          isvegan?: parameters["rowFilter.recipes.isvegan"];
          isvegetarian?: parameters["rowFilter.recipes.isvegetarian"];
          imgCode?: parameters["rowFilter.recipes.imgCode"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          recipeid?: parameters["rowFilter.recipes.recipeid"];
          photolink?: parameters["rowFilter.recipes.photolink"];
          title?: parameters["rowFilter.recipes.title"];
          description?: parameters["rowFilter.recipes.description"];
          recipetype?: parameters["rowFilter.recipes.recipetype"];
          mealportions?: parameters["rowFilter.recipes.mealportions"];
          kcalperportion?: parameters["rowFilter.recipes.kcalperportion"];
          verified?: parameters["rowFilter.recipes.verified"];
          proposaluserid?: parameters["rowFilter.recipes.proposaluserid"];
          isvegan?: parameters["rowFilter.recipes.isvegan"];
          isvegetarian?: parameters["rowFilter.recipes.isvegetarian"];
          imgCode?: parameters["rowFilter.recipes.imgCode"];
        };
        body: {
          /** recipes */
          recipes?: definitions["recipes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/usermeal": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.usermeal.id"];
          userid?: parameters["rowFilter.usermeal.userid"];
          mealdate?: parameters["rowFilter.usermeal.mealdate"];
          mealname?: parameters["rowFilter.usermeal.mealname"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["usermeal"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** usermeal */
          usermeal?: definitions["usermeal"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.usermeal.id"];
          userid?: parameters["rowFilter.usermeal.userid"];
          mealdate?: parameters["rowFilter.usermeal.mealdate"];
          mealname?: parameters["rowFilter.usermeal.mealname"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.usermeal.id"];
          userid?: parameters["rowFilter.usermeal.userid"];
          mealdate?: parameters["rowFilter.usermeal.mealdate"];
          mealname?: parameters["rowFilter.usermeal.mealname"];
        };
        body: {
          /** usermeal */
          usermeal?: definitions["usermeal"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          usertype?: parameters["rowFilter.users.usertype"];
          avatar?: parameters["rowFilter.users.avatar"];
          name?: parameters["rowFilter.users.name"];
          surname?: parameters["rowFilter.users.surname"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          usertype?: parameters["rowFilter.users.usertype"];
          avatar?: parameters["rowFilter.users.avatar"];
          name?: parameters["rowFilter.users.name"];
          surname?: parameters["rowFilter.users.surname"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          usertype?: parameters["rowFilter.users.usertype"];
          avatar?: parameters["rowFilter.users.avatar"];
          name?: parameters["rowFilter.users.name"];
          surname?: parameters["rowFilter.users.surname"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  favusersproducts: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    userid: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `products.productid`.<fk table='products' column='productid'/>
     */
    productid: string;
  };
  favusersrecipes: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    userid: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `recipes.recipeid`.<fk table='recipes' column='recipeid'/>
     */
    recipeid: string;
  };
  ingredients: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    ingredientid: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `products.productid`.<fk table='products' column='productid'/>
     */
    productid: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `recipes.recipeid`.<fk table='recipes' column='recipeid'/>
     */
    recipeid: string;
    /**
     * Format: numeric
     * @default 1
     */
    productcount?: number;
    /**
     * Format: public.measure_type
     * @enum {string}
     */
    measure:
      | "pinch"
      | "g"
      | "kg"
      | "teaspoon"
      | "tablespoon"
      | "glass"
      | "ml"
      | "liter"
      | "piece";
  };
  productinmeal: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `usermeal.id`.<fk table='usermeal' column='id'/>
     */
    mealid: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `products.productid`.<fk table='products' column='productid'/>
     */
    productid: string;
    /** Format: boolean */
    isEaten: boolean;
  };
  products: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    productid: string;
    /** Format: numeric */
    gtincode: number;
    /** Format: text */
    name: string;
    /** Format: text */
    photolink: string;
    /**
     * Format: public.product_category
     * @enum {string}
     */
    category:
      | "meat"
      | " eggs"
      | "fish"
      | " seafood"
      | "cereal products"
      | "milk"
      | " dairy products"
      | "preserves"
      | "drinks"
      | " juices"
      | " water"
      | "loose"
      | "spices"
      | "fruits"
      | "vegetables";
    /** Format: boolean */
    verified?: boolean;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    proposaluserid: string;
    /** Format: uuid */
    imgCode?: string;
  };
  recipeinmeal: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `usermeal.id`.<fk table='usermeal' column='id'/>
     */
    mealid: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `recipes.recipeid`.<fk table='recipes' column='recipeid'/>
     */
    recipeid: string;
    /** Format: boolean */
    isEaten: boolean;
  };
  recipes: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    recipeid: string;
    /** Format: text */
    photolink: string;
    /** Format: text */
    title: string;
    /** Format: text */
    description: string;
    /**
     * Format: public.recipe_type
     * @enum {string}
     */
    recipetype: "breakfast" | "lunch" | "dinner" | "snacks" | "dessert";
    /** Format: numeric */
    mealportions: number;
    /** Format: numeric */
    kcalperportion: number;
    /** Format: boolean */
    verified: boolean;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    proposaluserid: string;
    /** Format: boolean */
    isvegan: boolean;
    /** Format: boolean */
    isvegetarian: boolean;
    /** Format: uuid */
    imgCode?: string;
  };
  usermeal: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    userid: string;
    /**
     * Format: date
     * @default CURRENT_DATE
     */
    mealdate: string;
    /**
     * Format: public.meal_name
     * @enum {string}
     */
    mealname: "breakfast" | "supper" | "lunch" | "afternoon tea" | "dinner";
  };
  users: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: public.user_type
     * @default user
     * @enum {string}
     */
    usertype: "user" | "admin";
    /** Format: text */
    avatar?: string;
    /** Format: text */
    name?: string;
    /** Format: text */
    surname?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description favusersproducts */
  "body.favusersproducts": definitions["favusersproducts"];
  /** Format: uuid */
  "rowFilter.favusersproducts.id": string;
  /** Format: uuid */
  "rowFilter.favusersproducts.userid": string;
  /** Format: uuid */
  "rowFilter.favusersproducts.productid": string;
  /** @description favusersrecipes */
  "body.favusersrecipes": definitions["favusersrecipes"];
  /** Format: uuid */
  "rowFilter.favusersrecipes.id": string;
  /** Format: uuid */
  "rowFilter.favusersrecipes.userid": string;
  /** Format: uuid */
  "rowFilter.favusersrecipes.recipeid": string;
  /** @description ingredients */
  "body.ingredients": definitions["ingredients"];
  /** Format: uuid */
  "rowFilter.ingredients.ingredientid": string;
  /** Format: uuid */
  "rowFilter.ingredients.productid": string;
  /** Format: uuid */
  "rowFilter.ingredients.recipeid": string;
  /** Format: numeric */
  "rowFilter.ingredients.productcount": string;
  /** Format: public.measure_type */
  "rowFilter.ingredients.measure": string;
  /** @description productinmeal */
  "body.productinmeal": definitions["productinmeal"];
  /** Format: uuid */
  "rowFilter.productinmeal.id": string;
  /** Format: uuid */
  "rowFilter.productinmeal.mealid": string;
  /** Format: uuid */
  "rowFilter.productinmeal.productid": string;
  /** Format: boolean */
  "rowFilter.productinmeal.isEaten": string;
  /** @description products */
  "body.products": definitions["products"];
  /** Format: uuid */
  "rowFilter.products.productid": string;
  /** Format: numeric */
  "rowFilter.products.gtincode": string;
  /** Format: text */
  "rowFilter.products.name": string;
  /** Format: text */
  "rowFilter.products.photolink": string;
  /** Format: public.product_category */
  "rowFilter.products.category": string;
  /** Format: boolean */
  "rowFilter.products.verified": string;
  /** Format: uuid */
  "rowFilter.products.proposaluserid": string;
  /** Format: uuid */
  "rowFilter.products.imgCode": string;
  /** @description recipeinmeal */
  "body.recipeinmeal": definitions["recipeinmeal"];
  /** Format: uuid */
  "rowFilter.recipeinmeal.id": string;
  /** Format: uuid */
  "rowFilter.recipeinmeal.mealid": string;
  /** Format: uuid */
  "rowFilter.recipeinmeal.recipeid": string;
  /** Format: boolean */
  "rowFilter.recipeinmeal.isEaten": string;
  /** @description recipes */
  "body.recipes": definitions["recipes"];
  /** Format: uuid */
  "rowFilter.recipes.recipeid": string;
  /** Format: text */
  "rowFilter.recipes.photolink": string;
  /** Format: text */
  "rowFilter.recipes.title": string;
  /** Format: text */
  "rowFilter.recipes.description": string;
  /** Format: public.recipe_type */
  "rowFilter.recipes.recipetype": string;
  /** Format: numeric */
  "rowFilter.recipes.mealportions": string;
  /** Format: numeric */
  "rowFilter.recipes.kcalperportion": string;
  /** Format: boolean */
  "rowFilter.recipes.verified": string;
  /** Format: uuid */
  "rowFilter.recipes.proposaluserid": string;
  /** Format: boolean */
  "rowFilter.recipes.isvegan": string;
  /** Format: boolean */
  "rowFilter.recipes.isvegetarian": string;
  /** Format: uuid */
  "rowFilter.recipes.imgCode": string;
  /** @description usermeal */
  "body.usermeal": definitions["usermeal"];
  /** Format: uuid */
  "rowFilter.usermeal.id": string;
  /** Format: uuid */
  "rowFilter.usermeal.userid": string;
  /** Format: date */
  "rowFilter.usermeal.mealdate": string;
  /** Format: public.meal_name */
  "rowFilter.usermeal.mealname": string;
  /** @description users */
  "body.users": definitions["users"];
  /** Format: uuid */
  "rowFilter.users.id": string;
  /** Format: public.user_type */
  "rowFilter.users.usertype": string;
  /** Format: text */
  "rowFilter.users.avatar": string;
  /** Format: text */
  "rowFilter.users.name": string;
  /** Format: text */
  "rowFilter.users.surname": string;
}

export interface operations {}

export interface external {}
